#+SETUPFILE: ~/repos/org/resources/org-templates/new-setup/setup-barest-options.org

#+OPTIONS: pri:t

#+TITLE: Soundscapes

#+html_head: <link rel="stylesheet" type="text/css" href="../../../css/solarized-dark.css" />

#+infojs_opt: path:org-info.js
#+infojs_opt: toc:nil ltoc:above view:info mouse:underline buttons:nil
#+infojs_opt: up:http://orgmode.org/worg/
#+infojs_opt: home:http://orgmode.org 

#+INCLUDE: ~/repos/org/resources/org-templates/new-setup/setup-style-org1-FIX.org
* Introduction - What Is a Soundscape?

** 1. INTRODUCTION

*** A. Case Study: The Throat Singers of Tuva

1. Distinctive vocal method called khoomii

2. Musics from around the globe surround most of us where we live.

a. Accessible for an evening in concert or through the media

i. We can actively seek out new musical experiences.

ii. They also casually enter our perception.

b. The presence of multiple musics in familiar places is a reality of life worldwide in the twenty-first century.

3. Ethnomusicology unites the study of music with the concerns and methods of anthropology.

a. Depends on observation of and participation in musical events

b. Important moments in ethnomusicology


** 2. WHAT IS A SOUNDSCAPE?

*** A. The different aspects of the musical environment, ranging from a single musical tradition to all sounds heard in a particular place

1. A sonic environment that could be compared to a seascape

a. Flexible; music's ability both to stay in place and to move

i. Musical traditions can be anchored to one place for a long time.

ii. May move beyond the horizon

iii. May be blown off course unexpectedly

b. A flexible approach is needed to think about a soundscape's setting and aspects of sound and performance.

c. People’s interpretations of music’s significance are shaped by and contribute to shared patterns of knowledge and experience (culture).


** 3. LOCATING A SOUNDSCAPE

*** A. Sound

1. Individual voices and instruments are distinguished by differences in sound properties.

a. Studied through the field of acoustics
i. Each voice or instrument produces a blend of the fundamental tone and a series of tones above it.
ii. The harmonic series: an acoustical phenomenon
a. Tone quality called timbre
b. Each instrument and voice has a unique timbre.
2. Khoomii singers produce two tones at the same time.
a. Singer causes one additional partial to be heard above the fundamental.
b. Some singers can produce a third partial as well.
c. In other traditions besides khoomii, upper partials are audible.
3. There are many styles of khoomii with contrasting sound characteristics in different regions of the country.
a. Kargyraa
i. Has a lower-pitched fundamental and a husky voice quality
ii. May have a text
b. Sygyt
i. Has a higher-pitched fundamental
ii. Clear harmonics that sound like whistling
c. Many personal styles
i. Nose khoomii
ii. Chest khoomii

*** B. Setting
1. Includes everything from the venue to the behavior of those present
a. Reveals much about a musical event
i. Concert halls are constructed to contain musical sound.
ii. Music performed on street corners transforms a nonmusical venue.
iii. Recorded sound of a private experience might reach millions of listeners.
b. Determines, to a great extent, what we hear and see
i. Every musical event is influenced by others that came before it.
ii. Musicmakers must be creative in adapting their traditions to the situation.
c. The setting of each performance conveys meanings for both performers and listeners.
i. Traditional venues can be dramatically different from venues faced by musicians performing abroad.
a. Throat singing was a largely a solitary pursuit.
1. Particular settings shaped the musical sound.
2. Ezengileer is a notable example.
b. Throat singing is now performed on concert halls at home and abroad.
1. Singers adjust the length of music and perform in groups rather than as soloist.
2. Alternate singing with instrumental selections
3. Provide oral commentary

*** C. Significance
1. Music means, or signifies, different things to performers and listeners from different backgrounds.
a. Certain musical events can come to symbolize meaningful moments.
b. In other cases, music carries meanings that are hidden or hard to describe.
2. Khoomii is an example of a tradition with multiple meanings for performers and listeners.
a. By imitating natural sounds, singers reinforce their connection to the physical environment of Tuva.
i. Anchored in traditional Tuvan spiritual practices.
ii. Some Tuvans trace the origins of khoomii to lullabies.
iii. Khoomii may signify deep-seated associations with the homeland as well as ties to the family.
iv. Tuvans created musical representations of natural sounds of wind, water, and animals.
v. They shaped melodies to reflect features of the Tuvan topography.
b. Tuvan music is not considered by its musicians to as abstract but as “radically representational.”
i. Outsiders may be so surprised by audible harmonics that they do not consider the sounds’ significance.
ii. Repeated exposure can help outsiders become more sensitive to the range of meanings available to insiders.


** 4. THE EVER-CHANGING NATURE OF SOUNDSCAPES

*** A. Case Study: David Hykes and Harmonic Chant
1. In the early 1970s, the young American musician David Hykes heard a recording of khoomii from Mongolia.
a. Through experimentation, Hykes taught himself how to sing khoomii.
b. He also encountered the vocal techniques used by some orders of Tibetan monks to produces multiple harmonics.

2. Hykes formed the Harmonic Choir in 1975.
a. Ensemble of men and women who performed his compositions
i. Choir sang creating similar harmonics to those used in Tibetan chant.
ii. Hykes would sing a khoomii solo.
b. Performed in the Cathedral of St. John the Divine in New York City
i. Setting enhanced the sound and lent added significance
ii. Most of Hykes's performances were in resonant churches.
iii. Hykes believed music should be more than entertainment and should be a spiritual experience.
a. Conveyed universalist ideas shared by many New Age musicians
b. Presented concerts on days of universal significance

3. In 1987 Hykes moved to France.
a. Incorporated more styles into his solo khoomii-based compositions
b. Draws on improvisation during live performance
i. Cultivates a spiritual atmosphere while formulating a “new traditional or sacred art”
ii. Based on historical traditions, and at the same time constitutes a new beginning


* Chapter 1 - Sounds: The Materials of Music


** 1. WHAT IS MUSIC?

*** A. Silence is more often than not a relative concept—sound is ubiquitous

*** B. Music can be defined as organized sound that is meaningful to people within a specific time and place.

i. Some define music as organized sound with a melody
ii. Others define music by rhythm
iii. Closely related music cultures can also categorize the same sounds differently
a. Inuit define their katajjaq as a vocal game; however, closely related Chukchi and Ainu people consider similar songs to be music


** 2. CHARACTERISTICS OF SOUND


*** A. Quality: distinctiveness of a particular voice or instrument, also called tone color or timbre.

i. Sound Sources: The Voice
a. Vibrato: a purposeful vibration of the tone
b. Straight tone: a sound with little or no vibrato
c. Raspy: rough or gruff in quality in a singing voice
d. Chest voice: produces a low, powerful, throaty vocal production; this vocal quality is often heard in rock music
e. Head voice: produces a light, high tone that resonates in the head
f. Falsetto: the male head voice, produced by singing in a high register above the normal male singing range
g. Nasal quality: quality produced by using the sinuses and mask of the face as sound resonators

ii. Sound Sources: Instruments
a. Gamelan: large Indonesian instrumental ensembles
b. Steel drums: Trinidad, instruments made from modified oil drums, known as pans
c. Shakuhachi: Japanese flute associated with court and Zen monks
d. Different instruments may be closely identified with either men or women.
e. Instruments that are markers of ethnic and national identity can attain even deeper associations as people emigrate (Armenian duduk).
f. Instruments often carry prestige or status related to their historical roles in society (Ethiopian baganna).

iii. The Study and Classification of Musical Instruments
a. Organology: the study of musical instruments

b. Sachs-Hornbostel system: four-part classification system based on the means by which instruments produce sound (fifth category added later)

1. Idiophones: self-sounding instruments; the material of which they are made is set into vibration

2. Chordophones: sound source is one or more vibrating strings
a. Lutes: neck and body parallel to the strings.
b. Harp: soundboard to which strings are attached at an angle
c. Lyre: two distinctive arms and crossbar running between them to which the strings are attached
d. Zither: instrument with a flat body to which strings are attached parallel to the body

3. Aerophones: Instruments in which an enclosed column of air vibrates to produce sound; have an opening or mouthpiece through which the player blows air
a. Endblown: blown through a hole (mouthpiece) at the end
b. Transverse: blown through a hole on the side
c. Free reeds have enclosed reeds through which air is pushed.
d. Free aerophones act directly on surrounding air without enclosing it.

4. Membranophones: Characterized by a membrane (drumhead) stretched across one or both ends of the instrument. Classified by:
a. Shape: cylindrical, bowl (kettle), hourglass, or goblet
b. How membranes are attached (glued, tacked, laced, etc.)
c. Ways in which sound is produced (hands or sticks)

5. Electrophones: Instruments whose sound is produced or modified electronically

*** B. Intensity: The loudness or softness of a sound

i. Volume or dynamics

ii. Can be measured by a decibel meter

iii. Many music traditions have terms to describe intensity levels
a. Balinese gamelan
1. Keras refers to a strong, loud sound
2. Manis is a sweet, soft sound
b. Western classical music
1. Forte refers to a loud sound
2. Piano refers to a soft sound

*** C. Pitch: The relative highness or lowness of a sound, determined by frequency of the sound vibration

i. Hearing and Comparing Pitch Systems and Scales
a. The overall compass of pitches from highest to lowest that an instrument or voice can produce is called range.
b. The distance between pitches is called an interval.
c. A set of pitches arranged in order of ascent and descent is called a scale.
1. raga
2. mode
3. pentatonic scale

ii. Melody and Processes of Ornamentation
a. Melody: Organized pitches in meaningful units
1. Conjunct motion: Melody moves in close and regular intervals in a stepwise pattern.
2. Disjunct motion: Melody moves mainly in larger intervals.
3. Melodies can be decorated or ornamented.
4. Melodies are made up of phrases.

*** D. Duration: The time element of music

i. Pulse: A regular beat, like a heartbeat
ii. Rhythm: General temporal organization of music
iii. Tempo: Music's rate of speed
iv. Hearing and Comparing Rhythmic Systems
a. Meter: Hierarchical durational system divided into groups of beats called measures
1. Simple: Two, three, or four beats per measure
2. Compound: Six, nine, or twelve beats per measure
b. Syncopation: Rhythmic effect that provides an unexpected accent, often by temporarily unsettling the meter through a change in the established pattern of stressed and unstressed beats.
1. Many cultures use irregular or asymmetrical meters.
2. Some music is so flexible in its rhythmic organization that it is said to have free rhythm.


** 3. LISTENING FOR MUSICAL TEXTURE AND FORM

*** A. Hearing and Comparing Textures
i. Texture is the vertical structure of music, the perceived relationship of simultaneous musical sounds.
1. Monophony: Individual voice or instrument is performing alone (solo), or more than one voice or instrument sings or plays exactly the same melody

2. Biphony: Texture with two distinct lines, the lower sustaining a continuous pitch (drone) while the other performs a more elaborate melody above it
3. Homophony: Texture with a melody supported by other vocal or instrumental parts, all of which move along in roughly the same rhythm.
4. Polyphony: Combination of two or more different melodic lines
a. Polyrhythms: Several contrasting rhythmic patterns played simultaneously
5. Heterophony: Two or more voices or instruments produce almost the same melody at almost the same time; the parts are often ornamented differently.

*** B. Hearing and Comparing Forms
i. Form: The shape or structure of music
a. Strophic: Song structure in which all verses of text are set to the same melody
b. Refrain: Fixed stanza of text and music that recurs between verses of a strophic song
c. Many forms also have names
i. Ballad
ii. Middle Eastern sama‘i


** 4. PROCESSES OF MUSICAL CREATIVITY: COMPOSITION, PERFORMANCE, IMPROVISATION

*** A. Composition: Process of creating music

*** B. Improvisation: Spontaneous creation of music during performance


** 5. GEOGRAPHIES OF SOUND

*** A. Soundscapes that occur in the same geographic location often overlap and influence one another.
i. Musical styles move to different locations and have effects on other styles in different ways.
ii. Geographical Fugue





* Chapter 2 - Setting: The Study of Local Musics


** 1. INTRODUCTION: SETTING THE STAGE

*** A. Setting encompasses multiple contexts.
1. Soundscapes within several urban settings
a. The global rural-urban population balance has tipped in favor of cities.
2. Most communities are complex environments.


** 2. CASE STUDY: ACCRA, GHANA

*** A. Hearing Highlife in Accra
1. Highlife is a musical style.
a. The name originated during the 1920s.
b. Bands played popular tunes for upper-class audiences.
2. Unites several streams of the Ghanaian musical past
a. Sea chanteys and folk songs
b. Military bands
c. Piano music and church hymns
3. Central to Ghanaian life

*** B. Multicultural Accra
1. Location makes it a magnet for cultural exchange.
a. Incorporated into the British Empire
b. English is the official language.
2. Settlements by the Ga people in the fifteenth century
a. Portuguese were the first Europeans.
b. They were followed by the Dutch, Danish, and English.
3. Ga ethnic community lent distinctive cuisine and traditional music.
a. Homowo ("Mocking Hunger")Festival
i. Dance
ii. Drumming accompaniment
b. Various other festivals
c. Elaborate funerals
i. Expensive; can tax the resources of a family
ii. Full display of music and food
iii. Voluntary funeral associations: Milo Mianoewo
iv. Three-day affair
d. Agbadza dance
i. Popular social dance performed by Ewe men and women, sometimes at funerals
ii. Agbadza rhythms are, for many listeners, the most familiar aspects of the music.
4. Drums and their music are linked to other Ghanaian ethnic groups.
a. Agbadza rhythms associated with the Ewe people
b. Atumpan: a drum associated with the Akan people
i. Used for ceremonies by chiefs

ii.
iii.

“Male” and “female” drums played by one drummer Also played as talking drums, used in the past for communication

*** C. Music in Ghanaian Christian Life
1. A substantial amount of musicmaking in Accra occurs within the context of organized religious life.
a. Churches on virtually every block
b. The music unites Western musical influences with Ewe rhythmic complexity.
c. Many churches in Accra hold healing rituals.
i. The Kwabenya Prayer Camp of the Bethel Prayer Ministry International Church
ii. Songs, accompanied by instruments, are the main vehicle through which healing is accomplished.

*** D. Accra's Global Connections
1. The complex blend of local and international give the city's music a distinctive, cosmopolitan flavor.
a. Many different musics can be heard on Ghanaian radio.
b. Accra maintains an active and diverse cassette culture.
c. A number of musical ensembles reinforce national identity.


** 3. CASE STUDY: MUMBAI, INDIA

*** A. Mumbai has been the regional capital since India’s independence from
Britain in 1947.
1. A heterogeneous and global city: first settled by the Koli people, ruled later by Hindu and Muslim kingdoms, occupied by various foreign forces
a. Various linguistic, ethnic, and regional neighborhoods
b. Music ranges from distinctive local practices to national and international genres.
2. Despite its size and complexity, people acknowledge a sense of unity.
a. Various religions, ethnic backgrounds, economic statuses
b. Unity manifest in and supported by musical life

*** B. The Ganesh Chaturthi Festival
1. Hindu Ganesh Chaturthi festival leads off the pan-Indian festival season every fall.
a. Hindus are the majority in Mumbai, but there are many Muslims and Christians.
b. Community-wide festival promoting solidarity and independence from the British
c. Marks the birthday of Lord Ganesh, a popular Hindu deity

*** C. Music of Mumbai's Ethnic Communities
1. The Koli people, who were the first residents of the area, continue to be a presence in Mumbai.
a. Koli traditional culture is perpetuated.
b. Folk song recordings are distributed and broadcast.
2. Folk songs in Marathi are heard everywhere in Mumbai.
a. Lyrics address universal topics and subjects of local concern
b. Some are reintroduced and popularized through electronic remixes.
3. North Indian classical music is also actively represented in Mumbai.
4. European classical music has exerted an influence since British arrival.
a. National Centre for the Performing Arts
b. Bombay Chamber Orchestra

*** D. The Mumbai Film Industry
1. Film music is everywhere in Mumbai.
2. Indian film industry has mushroomed: Bollywood
a. Mass-marketed films known as "masala movies,” stereotyped, romantic plots with elaborate song and dance interludes throughout
b. Actors became superstars; “playback singers” also greatly admired
3. Early films used the Hindi and Urdu languages of Northern India.
a. Urdu language song genre, the ghazal, was very influential.
b. Strophic song accompanied by sarangi, tabla, and harmonium
4. Popular music from abroad and the international music industry have deeply influenced Indian film music.
a. Film song Mum-bhai from Bombay Boys
i. Reflects musical style of gangsta rap
ii. Text is in local dialect with some English phrases


** 4. CASE STUDY: BOSTON, USA

*** A. Why Boston?
1. Boston provides both a long history and exceptional ethnic, institutional, and musical diversity.
2. Boston provides a stimulating counterpoint to Accra and Mumbai.
3. In the nineteenth and early twentieth centuries, musical life closely tied to England and Europe.
4. Many Boston neighborhoods are also home to different socioeconomic and ethnic groups.
a. Former minorities within the city's longtime mainly EuroAmerican population became a majority.
b. Multicultural mixture of peoples has transformed and gentrified the South End.
5. Boston has more institutions of higher learning than any other North American city.

*** B. What Elements Make Up Boston's Musical Life?
1. The Boston Globe has a weekly musical calendar; provides a starting place for mapping musical Boston.
2. Genre categories for musical events include pop and rock; folk, world, and country; jazz, blues and cabaret, etc.
3. Early music, reggae

*** C. Where and When Is Music Performed?
1. Many soundscapes are associated with specific places and times.
a. Symphony Hall
b. Many other well-known performance spaces
c. Churches
d. Neighborhoods provide venues for many musical events.
2. Indoor and outdoor phenomena
a. Buskers in Harvard Square
b. City streets also provide a venue for special music events.
i. City Hall
ii. Boston Common and Public Garden

*** D. Who Makes the Music?
1. Irish
a. Immigration since the eighteenth century
b. Irish fiddling in pubs; bagpipes at civic and cultural events
c. Boston College's Gaelic Roots Festival each summer until 2003
d. Narrative songs, known as ballads, commemorate important events and memorable individuals.
i. The Ballad of Buddy McClean
ii. Simple and repetitive melody
2. Portuguese
a. From Portugal, Cape Verde Islands, and the Azores
b. A musical form popular with Bostonians of Portuguese descent is the fado.
i. Closely associated with the Portuguese capital, Lisbon
ii. Fado is sometimes compared with the blues.
iii. Portuguese Americans hear the fado largely through recordings imported from Portugal.
iv. Amália Rodrigues is thought to have personified the fado.
3. Cape Verdeans
a. Cape Verde was a way station between Africa, Europe, and Americas during slave trade.
b. Early immigrants to America settled in New England.
i. Cape Verdeans viewed as black in American society; language and culture kept them separate from African American community
ii. Distinctive culture expressed in food, music, and dance
c. Many Cape Verdean Americans have become prominent musicians
i. Maria de Barros was influenced by Cape Verdean, Latin American, and Caribbean styles.

*** E. Boston's Defining Musical Communities
1. Campus music
a. Many colleges and universities
b. New England Conservatory and Berklee College of Music
c. In the past, campus musical life mainly drew on Western music ensembles; avant-garde, popular, and international music has proliferated recently.
i. West African drumming at Tufts University
ii. North Indian and Senegalese music at MIT
d. Gamelan are prominent on many college campuses
i. Indonesian instrumental group
a. Instruments made of wood and bamboo, gongs, and instruments of xylophone type
ii. Major traditions from Java and Bali
iii. Gamelan is ubiquitous in Balinese life, has presence on college campuses around the world through Indonesia’s colonial history.
a. Symbol of Indonesian culture and national identity
b. Many composers drawn to sound of gamelan
1. Music organized in rhythmic cycles
2. Polyphonic texture
3. Beating tones
4. Interlocking parts
2. Folk music
a. Traditional folk music and folk music revival
b. Boston's importance in the folk music world
i. Boston's long liberal tradition and its many colleges made it a magnet for singer-songwriters.
ii. Over two hundred venues for live folk music performance in the Boston area
iii. M.T.A. Song
3. Early Music
a. Boston provided all the ingredients that allowed early music to flourish.
i. Magnet for professional musicians
ii. Many instrument builders
b. Early music ensembles incorporate diverse musical styles.
i. Early music and folk music cultures can converge.
ii. Barbara Allen

*** F. Boston's Distinctive Musical Profile
a. All three of Boston's major music cultures—campus music, folk music, and early music—are local as well as international, with deep roots in Boston as well as connections to other places.
i. The campus music scene is the most heterogeneous.
ii. The folk music revival is the most unified.
iii. Early music frequently crosses over to folk and world music.
b. University town par excellence





* Chapter 3 - Significance: Music’s Meaning in Everyday Life


** 1. INTRODUCTION

*** A. Significance: Music is able to elicit many ideas and emotions at the same time.

1. Meaning shapes our perceptions of music's importance in our lives in three ways:

a. Sound can imitate or refer to other sounds..
b. Sound can also signify entities or ideas within a soundscape.
c. Musical sound can also communicate specific meanings within individual cultures or subcultures.

2. Importance of a musical piece is determined by a listener’s understanding of a given music's meaning, and perceptions of its value to others within the same soundscape.


** 2. CASE STUDY: MEANING IN SOUTH INDIAN RAGA

*** A. Ragas are the Indian system for organizing melodies.

1. A raga can be associated with the time of day or the season of the year.
2. Each raga also has emotional connotations within an aesthetic system known as rasa.

a. Raga nilambari is closely associated with lullabies.
b. Can best be represented in Indian sargam notation.

i. Sa Ri Ga Ma Pa Dha Ni
ii. Each scale degree within a raga is called a svara.
iii. Each scale degree is combined with a type of ornament called a gamaka.

c. The Tamil word for “lullaby” is talattu, or "tongue rocking."

i. Vocables, araro ariraro, symbolize the motion of rocking a child.

d. Raga nilambari is mostly used for lullabies.
i. Considered to have a specific effect on the body
ii. Thought to have a sleep-inducing effect on both mortals and deities
iii. Also used in non-lullaby music, though that music is typically still thought to have a connection to sleep and lullabies


** 3. CASE STUDY: THE QUINCEAÑERA

*** A. La quinceañera, celebrated in Latino communities, marks a teenage
girl’s passage into adulthood.

1. Celebrates a chronological passage while acknowledging a particular cultural or ethnic identity and religious affiliation

a. Celebrated with a party or ball
b. A group of female and male friends acts as a court of honor.
c. Some urban Mexican American women are more likely to perceive the quinceañera less as an initiation into adulthood than as a symbol of historical limitations on women and their choices in society.

d. The music for the celebration depends in part on whether the family is of Mexican, Puerto Rican, Dominican, or another specific background.

e. Mexican American
i. Often hire live mariachi bands for the celebration
ii. Mariachi is a Mexican instrumental ensemble combining trumpets with plucked and bowed instruments of various types.

a. Common in Mexico and the southwestern United States
b. Mariachi musicians often dress like charros, the traditional Mexican horsemen or cowboys.

iii. Many songs performed at la quinceañera are not exclusive to that occasion


** 4. CASE STUDY: BAGPIPE MUSIC

*** A. The bagpipe is a wind instrument

with an air reservoir squeezed under one arm, a blowpipe or a bellows, and one or more sounding pipes fitted with reeds that vibrate to produce sound.

1. The history of the bagpipe extends well beyond its Scottish and Irish roots.
a. Archeological evidence of bagpipes in the ancient Middle East
b. The first known mention of a bagpipe (then called the utricularius) dates back to the reign of the Roman emperor Nero.
c. Scottish bagpipe mentioned in the prologue of The Canterbury Tales.

*** B. Sound
1. The instrument most widely played today in Irish and Scottish bagpipe bands is the Scottish Highland bagpipe.
2. Characteristic bagpipe ornaments are called grace notes or gracings.
a. The term cutting refers to the insertion of grace notes to divide a sustained sound.
b. Doubling describes a group of several grace notes.
i. A birl is a one type of doubling.
ii. Grips are several rapid grace notes in the lower part of the chanter's range.
3. Ireland has its own pìob mhór, or "great pipes."
a. Smaller than the Scottish highland pipes
b. Has a bellows rather than a blowpipe
c. Also known as the uilleann or "union" pipes.
i. In Ireland both highland (outdoor) and uilleann (indoor) pipes are played.

ii.

Only Scottish-style pìob mhór are allowed in international competitions.
4. Canntaireachd is a vocal style that imitates the pipes.
a. Vocables indicate bagpipe melodies and their gracings.
b. There were several systems of canntaireachd.
5. Bagpipes are strongly associated with men and historically male institutions such as the military.
a. Women were not typically prohibited from playing, but commonly were restricted to step dancing.
b. In recent decades, women have been encouraged to take up bagpipes.

*** C. Setting
1. Death and commemoration
a. Bagpipes have been linked symbolically with warfare and death since 1549.
b. Piobaireachd (pibroch) is a repertory of compositions that emerged through the MacCrimmon family of pipers.
i. Consists of:
a. The ground, or melody, which is always slow and longer than a march or dance tune
b. Extended variations on the ground
ii. Has long been used as a lament to commemorate a person’s death
c. In connection with the military, bagpipes have been associated with British imperialism.
i. Traditional dress, the kilt
ii. Heard throughout the Scottish and Irish diaspora
iii. Civic duties of pipers were absorbed into modern institutional settings.
a. Bagpipe bands associated with US police and fire departments
b. After the attacks on September 11, 2001, the FDNY Pipes and Drums squad played at the funeral of every firefighter lost in the line of duty
2. Entertainment and dance
a. Today the pipes are still heard at ceilidhs, festive gatherings that include music, socializing, and dancing.
i. Rooted in public dances that flourished in the eighteenth century.
ii. First consisted of a reel, a dance played by the bagpipe in combination with a slower strathspey.
b. The term ceilidh now refers to any social-musical event associated with Scottish or Irish traditions.
3. Competitions and concerts

a. Occasions of competition and public display have long been an important part of the history of piping.
b. William Cummings
c. Competitive performances featuring several bagpipe bands became common.
d. The bagpipe thus sustains a large musical repertory rooted in its history in Scotland and Ireland but also has traveled widely over the last century and a half.

*** D. Significance
1. Many meanings have accumulated over time, inspired by the pipes' presence in a range of settings.
2. Bagpipe music continues to accrue new layers of significance.
a. The 1979 film The Onion Field, and the book on which it was based, provide a fine example of the multiple meanings of the bagpipes, as constructed through the lens of literature and film.





* Chapter 4 - Music and Migration

** I. INTRODUCTION

*** A. Music is important to the migration process for several reasons
1. Music is portable.
a. In the past, music traveled only with human migration.
b. Recently, modern transportation has allowed for mass movements to occur more quickly.
c. Recording technology has reinforced musical transmission.
2. The presence of numerous transplanted musical traditions in a single place can have a variety of outcomes.


** II. VOLUNTARY MIGRATION

*** A. Voluntary migration is the movement of people to a new region by choice, motivated by an attraction to the new locale.
1. Each wave of migration to North America has had its impact.
a. British immigrants, beginning in the seventeenth century, carried ballads with them.
b. The ballads became associated with the mountains of Virginia and Kentucky.
2. Two important transmission processes for music:
a. Oral transmission: Music is passed from person to person through performance.
b. Written transmission: Music is passed from person to person in the form of written sources.

*** B. Case Study: The Chinese Migration
1. Chinese immigration, which began around 1850, was largely voluntary, motivated in part by the attraction that the United States held for many.
a. Some Chinese immigrants called the United States Jinshan, meaning “Gold Mountain.”
i. First immigrants were attracted by the California gold rush.
ii. Later immigrants came to work on the transcontinental railroad and to escape various difficult conditions in China.
b. Episodic immigration history
c. Many early Chinese immigrants considered themselves temporary residents in the United States.
i. Hoped They hoped to make money and return home.
ii. Since 1960, most Chinese immigrants have come to settle permanently.
2. The song Ng Bak Loi Gimsaan (“Uncle Ng Comes to the Gold Mountain”) traces and recounts details of the Chinese immigration process through music.
a. Traditional southeastern song genre called muk’yu (muyu).
i. Muyu are both transmitted orally and written down in songbooks.
ii. Muyu can be sung by men or women and are performed on a variety of occasions, both public and private.
iii. Muyu texts tell of the concerns of everyday life.
iv.Written muyu have a fixed form.
① Singer adds vocables in performance.

*** C. Case Study: Arab Migration from the Middle East
1. Waves of immigration
a. During the 1870s, immigrants from Greater Syria discovered an “entrepreneurial Eden” in the United States.
b. Migration after dislocation by the Arab-Israeli conflict
i. Chain migration
ii. Constant flow of new immigrants kept connections to the homeland alive.
c. Hanan Harouni is a Lebanese singer who settled in New York City after World War II.
i. Hanan sings mawwal, a traditional Arabic form that alternates sections in free and regular rhythms.
① The song in the recording is set in a contemporary Arab musical mode called huzam.
② Text is colloquial in language and content, commenting on the pain of migration.
2. Arab Americans maintain close ties to their homelands, and many of those connections are reaffirmed and symbolized through song.
a. Lebanese singer Fairuz (Nuhad Haddad) in Las Vegas in 1999
i. Used traditional instruments such as the ‘ud.
ii. Combined traditional Lebanese instruments with Western instruments such as the violin


** III.FORCED MIGRATION

*** A. Case Study: African Forced Migrations
1. Two causes of forced migration—conquest and slavery—continue to reverberate in the background of American life and musical styles.
a. Conquest, the westward expansion across North America, is celebrated in US popular culture, but:
i. Forced movement of millions of Africans through the slave trade
ii. Native American populations severely reduced through warfare and disease.
2. Many important musical repertories show traces of the painful experiences of African Americans during the slave era that followed their forced movement to the US.
a. Among the most influential of these repertories is the black spiritual.
i. Musical expression of slaves who converted to Christianity
ii. The first collection of spirituals was published under the title Slave Songs of the United States
① From oral tradition; originally sung in unison
② Later sung in call-and-response style

iii. Fisk Jubilee Singers traveled internationally and included spirituals in their public performances.
iv. Folk singers learned spirituals through oral transmission as well as from early recordings.
① Huddie Ledbetter(“Leadbelly”)
v. Black concert artists inspired by Fisk Jubilee Singers, notated sources, and renditions in the oral tradition, began to perform on the concert stage.
① Paul Robeson

*** B. Case Study: The Vietnamese Migration
1. The history of the present-day Vietnamese diaspora had its roots in the midseventeenth century.
a. French missionaries and French colonial control
i. Ho Chi Minh and the Communist North
ii. Division into North and South in 1954
b. American presence and the Vietnam War
i. Many Vietnamese forced to emigrate after the fall of Saigon
ii. Later waves of Vietnamese refugees fled mainly in small boats and makeshift rafts.
iii. Seventy percent immigrated to the United States, particularly the Gulf Coast and Texas.
2. Vietnamese diaspora communities in large urban centers have also hosted large popular musical events called da vu, or “night dance.”
a. These growing Vietnamese communities actively cultivate their music traditions.
b. Visiting troupes of musicians from Vietnam occasionally travel to diaspora communities.
3. The sound of Vietnamese instruments is often intended to elicit a strong emotional response as well.
a. Dan nguyet, a lute
b. Dan bau, a monochord instrument
i. Consists of a single string, a resonating chamber, and a small bamboo shaft
ii. Can produce a wide variety of sounds, even an imitation of the human voice
4. Music in Vietnamese refugee camps provides examples of how music is influenced by forced migration.
a. Many different musical styles.
b. People sang sad songs and love songs as an expression of political ideology.
c. Pham Duy’s music was heard in the camps, and he remains the bestknown Vietnamese composer in the diaspora.

*** C. THE NATIONAL ROAD SONG CYCLE
1. Pham Duy’s Con Duong Cai Quan (The National Road: A Voyage through Vietnam) is a song cycle incorporating several different streams of musical influence.

a. Tells of a traveler’s journey through Vietnam from north to south
b. Texts celebrate the cultural diversity and regional differences in the country and trace aspects of its history
c. Hybrid musical language with both Vietnamese and Western elements
i. One style, called tan nhac, combined Western instruments and
Vietnamese lyrics
ii. Nineteen songs divided into three sections representing:
① north Vietnam
② central Vietnam
③ south Vietnam
2. Sound
a. Song Come to Hue, Come for solo female voice
i. Pentatonic scale; modulation
ii. The harmony supports the pentatonic melodies.
b. Song Who Is Walking on the Endless Road for chorus and soloist
i. Combination of the word ho (pronounced “haw”), which means “to
raise the voice,” joined with vocables, signals Vietnamese roots
ii. Men’s and women’s voices alternate in call and response


3. Setting
a. Pham Duy’s compositions, like most Vietnamese musics, provide a basis
for reinterpretation, easily adapting to different performance contexts.
i. Come to Hue, Come
① Amateur singer and pianist
② Followed by popular dance music presented by local family
combo with electric guitars, keyboards, drums, and singer
ii. Who Is Walking on the Endless Road
① Arranged for synthesizer and performed in a symphonic
version
② Bridges the gap between Vietnamese immigrants and their
children born in the diaspora


4. Significance
a. The National Road had a powerful significance for the composer and
evoked a deep response from Vietnamese of the diaspora
b. Intended as a musical realization of a unified, independent Vietnam,
until recently it survived only abroad as an important musical symbol of
the continuing divide between the Vietnamese in their home country
and those in the diaspora.





* Chapter 5 – Music and Memory

** I. INTRODUCTION

*** A. Musical transmission is dependent on processes of remembering.

1. Song texts and melodies can remind us of people, places, and events.

2. Through repeated performances over time and in different settings, music draws on a partly subconscious bank of memories, sometimes triggering long-forgotten recollections and emotions.

3. The physical processes involved in musicmaking calls on what has been termed “habit memory.”

*** B. When we participate in or hear a musical performance, we experience a feeling similar to that in which a memory was first generated.

1. The study of musical transmission requires us to think about the processes of remembering.

2. Musicmaking depends on both individual and shared, or collective, memories.


** II. REMEMBERING THROUGH MUSIC

*** A. Case Study: The Corrido
1. The Mexican corrido (ballad) is an example of the ability of music to convey
memories of particular places, people, and events.
a. In the corrido, as in most other ballads, memories are carried
primarily in the text.
b. The melody supports that text and helps the singer recall it during a
performance.
2. The corrido first emerged in the second half of the nineteenth century as a
song genre shaped by intercultural conflict.
a. Influenced by conflicts between Mexicans and Americans in the
Mexican–US border region
b. Became a medium through which Mexicans and Mexican Americans
could respond to American domination
3. Corridos of the late nineteenth and early twentieth centuries focused on the
actions of important individuals, recounted in hero corridos.
a. The corrido Gregorio Cortez is a famous example of this repertory.
i. Portrayal of larger-than-life Mexican figures
ii. Important to Texan Mexicans
iii. The corrido underwent a period of decline and transformation
after its great popularity in the 1910s and 1920s.
4. The texts about heroes were replaced with what have been termed
victim corridos.
a. Emerged in the 1930s just as Mexican American society was becoming
part of a more urban, Americanized culture
b. Used song to inspire the Mexican American community to take
collective action on the victims' behalf
5. New revolutionary corrido repertory arose that commented on social and
economic hardships.
a. Critiqued the Mexican political situation in the 1990s

6. Narco-corridos, or "drug ballads," also have beenpopular in recent decades.
a. Compared with gangsta rap
b. Widely performed by popular groups such as Los Tigres del Norte
i. Intended as constructive criticism, not praise
ii. Many of the songs speak of the difficult lives of Mexican
immigrants to the United States.
7. In the twenty-first century, the corrido continues to chronicle major events
and ensure they are remembered through music.
a. Black September commemorates the attacks of September 11, 2001.
b. The Ballad of Osama bin Laden adapts the classic hero corrido format
to interrogate the motives of the commander of the same attacks.


** III. COMMEMORATING THROUGH MUSIC

*** A. Case Study: The Jazz Funeral
1. Marks the death of a musician or some other person of note.
2. Louis “Satchmo” Armstrong had two funerals:
a. A conventional ceremony near his home in New York City
b. Old-fashioned jazz funeral in New Orleans, the city of his birth
i. Features a jazz band, which improvises on both the melody and
accompanying parts of popular songs
a. The band leads a procession, followed by a hearse
carrying the coffin, mourners, and members of the
funeral association
ii. At the cemetery, the band plays hymns (sacred songs for
worship) and dirges (slow instrumental laments)
iii. Music played during the return from the cemetery is a fast,
lively repertory, in accordance with African American belief
that the funeral is not only a farewell, but also a celebration of
the person's life and a time for rejoicing.
a. Onlookers join the second line, a crowd that follows the
band and the mourners as they process through the
streets.
b. Once the band is a respectful distance from cemetery, it
plays lively marches or popular tunes that contrast with
the solemn hymns played on the way to the cemetery.


** IV. RECONCILING MEMORIES THROUGH MUSIC

*** A. Case Study: The Syrian Jewish Pizmon
1. Music can sustain memories that seem at odds with the present-day settings
in which the music is transmitted.
a. Pizmon literally means “adoration” or “praise.”
i. Most of these hymns consist of Hebrew texts set to melodies
borrowed from Middle Eastern Arab music.
ii. Syrian Jews have continued to sing these hymns and have also
composed new pizmonim.
2. The sound of the pizmon

a. The pizmon tradition had its beginnings in the late Middle Ages.
i. Contrafactum is the use of a preexisting melody with new text.
ii. The use of well-known, preexisting melodies ensures that the
new text will be remembered more easily.
b. Most pizmonim borrow tunes from Arab songs and are based on the
Arab musical system of maqam.
i. Maqam are the core of Arab music.
ii. Each maqam is a category of melodies that share pitch content,
range, and characteristic ornaments.
iii. There are at least a dozen important categories of maqamat,
each distinguished by its pitch content and ornaments.
a. Scales based on tetrachords
c. Syrian Jews prescribe one maqam to be emphasized each week.
Selected pizmonim and important prayers are sung in the
weekly maqam.
i. Maqam nahawand from the late nineteenth century has
remained popular into the present time.
a. Sounds similar to the minor scale of Western music.
b. Western notation helped standardize maqam.
c. Pizmon Attah El Kabbir is an interesting case study of
musical transmission. It spread as Syrian Jews migrated
from Syria to other places.
d. Has a layali (improvised vocal introduction) that
establishes the maqam of the subsequent song.
e. Pizmon melody maintains a well-known Arab three-part
form, the muwashshah.
ii. Maqam ajam is very similar to the Western major scale.
a. Resembles Western melodies
b. Not based on Arab sources
3. The settings of pizmon performance
a. Most performed to celebrate births, bar mitzvahs, weddings, etc.
i. A new pizmon is often composed for the birth of a baby.
ii. If a given pizmon becomes popular, it can be performed at
subsequent events and enter the chain of musical transmission.
b. Important setting for pizmon transmission is a Sabbath afternoon
songfest called the Sebet
i. Plays a major role in Syrian Jews’ ceremonial and social life,
including helping to reinforce memories
ii. Transplanted through migration
iii. Includes only unaccompanied pizmonim sung in Hebrew
c. Pizmonim are also performed at parties known as haflah that
celebrate special occasions, such as anniversaries.
i. Performers sing the original songs from which
the pizmon melodies have been taken, complete with their
Arabic texts.
ii. Songs in Arabic with instrumental accompaniment.

4. Musical sources for diaspora pizmonim
a. Pizmon melodies have been drawn from many sources, including from
music traditions Syrian Jews encountered in their new homelands.
b. Mifalot Elohim, written for a wedding in New York City, became a
popular pizmon for a time.
i. Based on the groom’s high school song, which had also been
based on the Christmas carol O Tannenbaum.
ii. Rarely sung in Syrian Jewish circles because they began to
associate its melody with Christmas rather than the school
song.
iii. Classified as maqam ajam, even though not an Arab source.
5. Continuing use of Arab melodies
a. Pizmonim depend most heavily on the Arab musical tradition for their
inspiration.
b. Pizmon Ramah Evarai was composed for a bar mitzvah.
i. Also used for the dedication of a newly copied Torah scroll the
same day as the bar mitzvah.
ii. Based on the Arab song The Wheat Song
a. The Wheat Song was composed by Muhammad Abd alWahhab, who is known as an innovator in Arab musical
style.
b. The Wheat Song was very popular.
A. Composed for a movie in 1946
B. Recordings were circulated widely

iii. The pizmon composer Louis Massry chose the melody of The
Wheat Song because it was memorable.
a. By borrowing a melody from this song, the pizmon
carries memories of Middle Eastern life.
b. The Hebrew contrafactum text has many hidden
meanings, with references to Jewish law and custom.





* Chapter 6 - Music, Mobility, and the Global Marketplace


** 1. INTRODUCTION

*** A. Global forces shape present-day musical transmission and performance.
1. New settings for musical performance have opened new channels of
musical transmission.
a. International educational exchanges, recordings, broadcasts,
festivals
b. Historical roots in the nineteenth-century colonial era and
exhibition culture in Europe and the United States
2. The juxtaposition of musical traditions within the same settings has
also resulted in exchanges among musicians who did not formerly
interact.

*** B. All micromusics—small musical units within big music cultures—can be situated within three interacting and overlapping levels.
1. Subculture: includes local, personal, familial, occupational, and
community networks
2. Interculture: subcultures' influence on each other through economic
or commercial connections, proximity, or affinity
3. Superculture: shaped by the power of the state and by the national
and global economy


** 2. TRAVEL AND TOURISM

*** A. Case Study: The Hawaiian Sound
1. The exhibition and sale of music as part of tourism became a lucrative
industry in many places long before the middle and late twentieth
century.
a. Sounds of the steel guitar and ukulele, as well as the swaying
movements of the hula dance, became inseparable from the
burgeoning Pacific tourist trade.
b. These sounds and sights came to signify Hawaii.
2. Some of the foremost performers responsible for the global marketing
of Hawaiian music were not native Hawaiians.
a. The Moe family spent virtually all of their adult lives abroad.
i. Born in Samoa; moved to Hawaii at an early age
ii. The brothers eventually split up into separate
ensembles.
b. Signed in 1941 by the impresario Felix Mendelssohn
i. The group became quite well known in Europe and Asia.
ii. Mendelssohn promoted the Pulu Moe ensemble
vigorously, marketing them as "foreign" and "exotic."
iii. After Mendelssohn’s death, the Moe Trio disbanded.
a. Pulu Moe worked in a factory in London and
returned to Hawaii in 1962.

b. Tau Moe family continued to tour and returned
to Hawaii in their eighties.
3. The ukulele has enjoyed several waves of popularity in North America.
a. The popularity of the steel guitar and ukulele spread to North
America first during the ukulele craze of the 1920s and 1930s.
b. Revived through LP recordings in the 1950s
c. Recent restoring and remastering of historic Hawaiian
recordings
d. The third great ukulele era began in 2006 with Jake
Shimakukuro’s performance on a viral YouTube video.
4. Since the 1970s, Hawaii has seen a resurgence of interest in its
indigenous music and hula dance traditions.
a. Hula is popular internationally as well.
i. There are approximately forty hula schools in Holland,
more than six hundred in Mexico, and about one
thousand in Japan.
a. Hawaiian music and hula have become
enormously popular among young Japanese
women.
b. Today, ukulele lessons are aired on Japanese
television.
b. Hawaiian music is found internationally in surprising locales.
i. Hula and ukulele workshops and classes are held
throughout the United States.
ii. Hawaii-based dance groups focus entirely on the hula.
iii. Many in the continental United States teach, perform,
and maintain many Polynesian dances.
5. The wide array of internationally dispersed Hawaiian music and
dance traditions testifies to the impact of tourism on music.


** 3. INTERCULTURAL TRANSMISSION AND BOUNDARY CROSSING

*** A. Case Study: New Music for Balinese Gamelan
1. Gamelan internationally supported by the Indonesian government to
represent indigenous musical traditions abroad.
a. Gamelan has influenced many outside of Indonesia.
i. Inspiring new compositions for the traditional
ensemble
ii. Inspiring some composers to build their own newly
designed gamelan and to write music for them
b. Gong kebyar style was performed by a new gamelan ensemble
in the first decades of the twentieth century.
2. New Balinese gamelan began to attract national and international
attention
a. Balinese dancers and musicians performed to great acclaim at
the 1931 International Colonial Exposition in Paris.

i. Bali became a chic tourist destination.
ii. Bali became the fashion in many distant places.
b. Following Indonesian independence in 1945, Balinese culture
was pushed to the fore as an international symbol of Indonesia.
i. A gamelan gong kebyar was installed at the Presidential
Palace in Bali.
ii. Music also continued to play a powerful role in the
internal Balinese political process.
c. In the 1960s, the institutional settings for transmission
of gamelan gong kebyar music were altered.
i. Government-sponsored schools for music, dance,
shadow puppetry, and visual arts were established in
Bali.
ii. Schools' staffs included increasing numbers of Balinese
musicians who had received some of their training
abroad.
iii. The music continues to be multidimensional and
embodies the contradictions, continuities, and
instability of twentieth-century Balinese history.
3. One well-known Balinese composer at work today is I Nyoman
Windha.
a. First made his reputation as an accomplished ugal player
i. Began composing in 1983
ii. Produced numerous works well known both in Bali and
abroad
a. Traveled often among Indonesia, the United
States, and Germany
b. In 2003, Windha moved to California
b. Worked closely with Gamelan Sekar Jaya
i. Windha composed Kembang Pencak.
a. Pencak is a type of martial arts from Indonesia,
and kembang means "blooming."
b. Musical genre: kreasi baru
ii. Characterized by diverse ingredients
a. Unstable and asymmetrical sections
b. Quick changes of texture and tempo
c. Windha joined Berkeley's gamelan Sekar Jaya for a year-long
residency.
i. Met Evan Ziporyn
ii. Kembang Pencak became the model for a new piece
titled Kekembangan.
a. Highlights differences between Balinese and
American musical systems and ways of hearing
b. Substitutes a saxophone quartet for the male
singers


** 4. MUSIC AS ART AND COMMODITY

*** A. Case Study: Traveling the Silk Road
1. The Silk Road's new settings
a. The historical Silk Road provides an extraordinary tale of the
extensive movement of people and music.
b. Twentieth-century elaboration on the Silk Road theme
conceived by the renowned cellist Yo-Yo Ma
i. Launched the Silk Road Project to study the “historical
and present-day flow of culture and ideas along the
trans-Eurasian trade routes”
ii. Hopes to plant the seeds of new artistic and cultural
growth
c. Yo-Yo Ma provides a model for musical mobility.
i. Performs in a range of styles, crossing frequently and
deliberately between soundscapes
ii. Has collaborated with other classical musicians
iii. Performs with musicians well established in other
musical styles
a. Hush with Bobby McFerrin
b. Grammy for Soul of the Tango
c. Collaborated with Cuban and Brazilian musicians
to produce Obrigado Brazil
2. Connecting Silk Road sounds and significances
a. Ma launched a cross-cultural project with two goals.
i. To present music and musicians from cultures along the
ancient Silk Road
ii. To commission new music from composers from these
regions
b. Ma himself has become an active force in initiating musical
transmission.
i. Project began its life as a global musical initiative
drawing heavily on subcultural and intercultural
musical resources.
ii. It sponsors concert tours by traditional musicians,
produces recordings, and collaborates with institutions
to produce festivals on the theme of the Silk Road.
iii. The project required considerable financial resources,
mainly obtained through global corporate sponsors.
c. An important goal of the Silk Road Project is to bring attention
to diverse musical traditions from along the historic Silk Road.
i. Many of the project’s musicians were already known to
international audiences.
a. Chinese musician Wu Man, a virtuoso player on
the Chinese plucked lute, the pipa.

b. Already established on the global musical scene
d. Ma has worked actively to both commission and perform
music.
i. The Silk Road Ensemble
ii. Silk Road Journeys: When Strangers Meet
e. The Silk Road Project also organized educational projects
around the world.





* Chapter 7 - Music and Dance


** 1. INTRODUCTION

*** A. Like music, dance exists in time and space.

*** B. Dance and its musical accompaniment are so closely joined that both are often known by the same name.
1. Dance almost always makes a statement about its time and place, and about the people who are performing it.
2. Dances can reflect and express a range of emotions.

*** C. Dance enacts the most important values of a soundscape and communicates and reinforces these ideas.
1. Dance ethnologists specialize in dance studies.
2. Choreometrics allows for measurement of many types of movement.
3. Recently, scholars have become more concerned with the meaning of
dance.


** 2. HEARING AND FEELING THE DANCE

*** A. Case Study: The Union of Dance and Martial Art in Capoeira
1. Capoeira, a centuries-old Afro-Brazilian performance style, combines
elements of martial arts, dance, and music.
a. Two competing players perform stylized motions.
b. They are accompanied by a capoeira orchestra called the
bateria.
c. Movements are based on the “sway” (ginga), continuous
motion of the player’s body from side to side in wide-legged
stances.
2. The berimbau is the main instrument of the bateria.
a. Musical bow with a gourd resonator
i. The player holds the bow upright in one hand, pressing
a coin or stone against the string to change its pitch and
quality.
ii. The player holds a stick and a small wicker rattle filled
with seeds in the other hand, striking the string with the
stick.
b. The instruments of the bateria accompany songs with
Portuguese-language texts.
3. Capoeira commemorates strong elements of resistance against a
series of injustices to its Afro-Brazilian performers.
a. Some historians suggest that capoeira is descended from an
Angola combat game called n’golo.
i. Accompanied by a musical bow.
ii. Similar combat games are played across west, central,
and southern Africa, and use of musical bows across the
continent is widespread.

b. Capoeira emerged among the African slaves who worked in
plantations and mines, spreading to those performing other
forms of labor.
i. Differing regional styles
4. Capoeira’s history has three main periods
a. The slavery period (seventeenth, eighteenth, and nineteenth
centuries until 1888):
i. Ruling classes disapproved of capoeira and repressed
participation.
ii. In the nineteenth century, greater numbers practiced it
as a “game.”
b. The underground period (1892 until the 1920s):
i. The Brazilian government prohibited capoeira gangs.
ii. Musicians and artists from abroad became interested in
African traditions in the Americas.
iii. In 1922, the Brazilian Modernist movement began
exploring Afro-Brazilian culture.
c. The academy period (1920s onward):
i. Capoeira academies were established through the
efforts of masters (mestres).
a. Mestre Bimba
1. Founded the regional style associated
with Bahia
2. Developed a system of seven
melodic/rhythmic patterns called toques
3. Reduced use of drum, changed order of
roda ritual, added ceremonies
b. Mestre Pastinha
1. Focused on capoeira’s African roots and
its status as a sport
2. Advanced capoeira as a means of “selfcontrol and education”
3. Emphasized role of melody, rhythm, and
song texts
ii. Today, capoeira is a global phenomenon.
a. Masters are publicly recognized.
b. The use if berimbau has expanded beyond
capoeira.

*** B. Case Study: Moving through Time and Space with Bhangra
1. Bhangra is a dance tradition that originated in the Punjab region of
India and is now associated with South Asian diaspora communities in
Great Britain and North America.
a. Originally referred to the rhythms played by the dhol drums
i. Two-headed drum beaten with curved sticks
ii. Each head has a distinctive sound.

b. Giddha: closely related dance for Punjabi women, accompanied
by hand-claps rather than drums
c. The dhol rhythm, jhummar, originated in Punjab.
d. Other instruments were used with the dhol drums:
i. Bugdu: a monochord
ii. Algoza: a double flute
iii. Chimta: an idiophone
2. Bhangra in the diaspora
a. Bhangra might have remained a regional harvest dance had
many Punjabis not migrated to Britain in the early 1950s.
i. By the 1960s, bhangra provided a context in which
South Asian youths could affirm their cultural identities
in a positive way.
ii. By the late 1970s, a number of amateur Punjabi groups
were performing traditional bhangra at community
events.
iii. By the early 1990s, bhangra styles had emerged in
Great Britain and abroad and had crossed over into the
mainstream.
b. In North America, bhangra performance spread to schools and
college campuses.
i. Many campuses now have bhangra clubs.
ii. Many students view participation in bhangra as a way
to construct a relationship with the traditions of their
Punjabi-born parents.
c. Many bhangra styles, including rock bhangra, house bhangra,
and bhangramuffin, have used new technologies and sampling
combined with acoustic instruments.
i. However progressive its sounds and references to
gender and sexuality in the texts, bhangra movements
represent traditional South Asian notions of clear
gender roles.
a. Often separate male and female teams at
competitions
ii. Aao Nachiye was a bhangra hit of the mid-1990s
performed by the Sangeet Group.
a. Use of synthesizers and electronic manipulations
b. Retains a number of traditional elements
d. In recent years, bhangra has moved well beyond college
campuses to enter the professional "Indipop" scene.
i. Bhangra has also been performed regularly at clubs in
England and in urban North America.
ii. Bhangra and hip hop are partners in creating new
hybrid styles.

iii.

Elders in the Punjabi community have questioned
bhangra’s departure from its historical roots and
sounds.
e. Although bhangra is malleable in many ways, it has several
features that are stable and that have become its defining
characteristics.
i. Repetitive movements such as jhummar
ii. Strong, regular dhol rhythms
iii. Punjabi texts


** 3. DANCE STYLES AND THEIR MULTIPLE MEANINGS

*** A. Case Study: The Tango
1. Sound and steps
a. The tango's musical foundation is a quadruple meter strongly
emphasized in the bass.
i. Features habañera rhythm, named after the Cuban
rhythm from which it was derived
b. Circular dance with steps that progress counterclockwise
i. Includes a number of standard motions
ii. Some steps are also used in Latin dances such as
the chachachá and rumba.
c. Played by the orquesta típica
i. Piano, violin, and bandoneón.
ii. Eventually became larger ensembles
2. Around 1910, tango dances began to be sung with texts.
a. The singer most responsible for the internationalization of the
tango was Carlos Gardel.
i. He was a major force in popularizing the tango in Paris
and in Argentina.
ii. Tango's popularity spread through nightclub
performances and recordings, radio, and film.
b. Tango lyrics drew on the lunfardo, a lower-class dialect of
Buenos Aires.
i. Organ grinders (organitos) also played tangos
throughout the streets.
c. Migration of the tango to Europe insured its upward mobility
in Argentina.
i. Buenos Aires followed Paris's lead in welcoming the
tango to upper-class cabarets and theaters.
3. New sounds for the concert hall
a. Astor Piazzolla created a purely instrumental "new tango," not
intended for dancing but for the concert hall.
i. Retained the sound of the bandoneón-centered tango
ensemble while expanding the rhythmic and harmonic
complexity of the music

ii.

Reshaped its sound to span the divide between popular
and classical music
iii. New tango ensemble includes several bandoneóns,
strings, and percussion instruments, as well as piano
b. European classical composers such as Igor Stravinsky had
already incorporated the tango into their compositions.
c. As the tango spread, different dance styles developed.
i. Argentine style: performed in a close embrace
ii. International style: simpler than the Argentine tango,
highly choreographed for competitions
iii. American style: a social dance, although it is performed
in competitions as well
4. Significance
a. The significance of the tango remains a source of dispute in
Argentina.
i. Themes of overt sexuality and male dominance are
embedded in the choreography of the dance.
ii. Body language incorporates and perpetuates notions of
masculine dominance.
b. As the tango spread, it was considered exotic and was
exploited as a commodity.
i. Holds great significance for its many aficionados who
are enthralled with the grace and rhythm of the dance
ii. There are tango clubs throughout the world, including
in Argentina, Germany, and Japan.






* Chapter 8 - Music and Ritual


** 1. INTRODUCTION

*** A. Public celebrations of religious belief have provided important settings for musical performance.
1. Rituals may extend well the boundaries of religious belief.
a. Ritual, sacred service, liturgy, and liturgical order are terms
used interchangeably to refer to public acts of worship.
b. Rituals tend to share a common structure.
i. Incorporate a symbolic process or change of state
ii. Three stages of a cultural ritual: separation, transition,
and incorporation
2. Music often provides clear markers of the stages in a rite of passage.
a. A ritual guides its participants through time in special ways.
b. Music and movement can be crucial to expressing what cannot
be conveyed through words.
3. The ability of ritual to evoke a strong emotional and physical response
is shaped through different means in different soundscapes.
a. There is no single musical pathway to transcendence.
b. The ritual process can also have very different outcomes.


** 2. THE CENTRALITY OF CHANT

*** A. Case Study: Tibetan Buddhist Chant
1. Chant may sound simple, but its musical surface can mask
extraordinary depths of meaning.
a. Tibetan Buddhist chant provides an example of such complex
significance.
b. Performing chant is instrumental in moving the singer through
the ritual process to a transformed state.
c. Ritual meditation text (sadhana) evokes the sacred and helps
the monk visualize and unite with the deity.
2. The biphonic vocal style of the monks includes a low fundamental in
the bass as well as a harmonic high above it.
a. Sound is actually two harmonics, the fifth and the tenth.
b. The fundamental slowly rises and falls throughout the
Mahakala ritual.
i. Elaborate ritual comprised of sustained sections of
chant (dbyangs)
ii. Accompanied by cymbals, drums, and horns
c. The “Tantra voice” is used in sound rituals associated with
Tantric belief and philosophy
3. Study of the rol mo musical repertory has shown that it contains a
complex mathematical organization of rhythmic structures.
a. Rhythmic complexities require training and experience to
perform and perceive.

b. The rhythms are not metered, cyclical, or irregular; they are
free rhythmic patterns.
4. Chant has occasionally been presented in public performance.
a. Chant has also been performed in recent years to gain political
and financial support for Tibetans exiled from their homeland.
b. It has been used in a range of popular contexts, including car
commercials on television.


** 3. THE CHANGING CONTEXTS OF RITUAL PERFORMANCE

*** A. Case Study: Santería
1. Afro-Cuban religion derived from West African beliefs, language, and
practices that were transplanted to the Caribbean and combined with
some aspects of Catholicism.
a. Large numbers of Africans were imported in a final wave of
slavery as late as the mid-nineteenth century.
b. African slaves in Cuba managed to create social institutions
that perpetuated and transformed the traditions they had
brought with them.
i. Cabildos are organizations established in Cuba by
Africans who had shared roots in the same African
linguistic and cultural group.
ii. They were increasingly regulated by the Cuban
government over time.
a. Legal restriction in 1888
b. Practiced informally and in secret
c. Worshiped orishas or santos, which joined African deities with
Catholic saints
i. Each was associated with particular herbs and plants,
and further associated with its own chants, drum
rhythms, and dance movements.
ii. Complex rituals sought to help practitioners achieve
divination and trance states.
d. The goal of Santería worship is to establish a relationship with
the orishas.
i. Animal sacrifices are made in hopes of obtaining help
from the orishas with the problems of daily life.
ii. Worshipers of the orishas came to be called santeros.
2. Within the rituals of Santería, batá drums summon the orishas at
certain times.
a. The santero or santera will be possessed or "mounted" by
an orisha.
b. Possession is regarded as dangerous for those who are not
spiritually developed.
3. Chanting has long been an important part of the Santería rituals.

a. Chants were almost always performed in call-and-response
style.
b. A chant is identified with a particular orisha.
i. Chants differ in their content and function.
ii. Their power is to communicate with the divinities—to
"bring down" the orishas.
c. As the Santería belief system was adopted throughout the
diaspora, some of its Catholic practices were abandoned.
i. Emphasis was placed instead on the rituals associated
with its African roots.
ii. New performance settings arose, with some
practitioners taking the controversial step of opening
formerly secret rituals to the public.

*** B. Case Study: Ethiopian Christian Chant
1. The Ethiopian Christian Orthodox Church
a. One of the oldest Christian denominations in the world
i. Close relations with the Coptic Church of Egypt
ii. Church stood at the center of Ethiopian religious life
and the political and cultural life of the people.
b. Overthrow of Emperor Haile Selassie in 1974 diminished the
status of the church.
i. Millions were forced to leave Ethiopia.
ii. Ethiopians established diaspora communities.
2. Ethiopian chant in its historical homeland
a. Ethiopian Christian chant is called zema.
i. Attributed in traditional Ethiopian sources to the divine
inspiration of Saint Yared
ii. Transmitted primarily through oral tradition
iii. System of musical notation helps sustain musical and
liturgical transmission.
b. Main setting for elaborate chant performance is the ritual
called the Mahlet.
i. Performed for hours throughout the night on holidays
ii. Includes nearly two dozen types of chants
3. Sound
a. When a large number of church musicians (debtaras) are
present for rituals, chants are sung with different forms of
instrumental accompaniment and dance.
i. Musicians wave prayer staffs; when chant is repeated,
they are accompanied by sistra, small metal idiophones
shaken in repeated patterns of three, four, five, or more
beats.
ii. Two kebaro drums enter, playing rhythmic patterns
that overlap with sistra.
iii. As the pace increases, musicians begin to dance.

b. Yome fesseha kone in Ge'ez mode
i. Sung as part of the Ethiopian ritual for Christmas
ii. Ge’ez involves distinctive vocal slides called rekrekk.
iii. In the liturgical setting, this chant is preceded by the
singing of hallelujahs.
a. Plainchant style
b. Antiphonal style
c. This chant can help us understand the extent to which pitch is
perceived differently across cultural boundaries.
i. Ethiopian notational sign (melekket) represents a short
melody.
a. The melekket is the smallest musical unit.
transmitted by Ethiopian church musicians.
b. Several melodies linked together constitute a
phrase of the chant.
ii. Debtaras do not hear the chant as consisting of a series
of individual pitches.
a. Learn entire chant as performed in ritual.
b. Practice by repeating short phrases after the
teacher.
4. Ethiopian chant in its North American diaspora
a. Ethiopian Christian Orthodox Church has established itself
outside Ethiopia after revolution of the 1970s.
i. Many urban areas support several Ethiopian
congregations.
ii. Most of these congregations lack their own meeting
spaces and depend on the generosity of other Christian
denominations.
b. Challenges confront Ethiopians of the diaspora seeking to
sustain their religious and musical practice in North America.
i. Ethiopian Americans have established both community
organizations and extensive social networks.
ii. Difficult to gather the necessary funds to sustain even a
modest Ethiopian Christian ritual cycle
a. Severe shortage of qualified clergy
b. The Ethiopian church's music traditions are
placed at particularly high risk in the diaspora.
c. Ethiopian Americans sought to bring liturgy closer to other
American Christian denominations.
i. The regular performance of the Hymnary is mounted
only on special occasions.
ii. Performances of chant lack the polish of Ethiopian
versions.
iii. Fewer chants are remembered and are no longer
perceived in the traditional way.

5. The impact on liturgical music of changing settings at home and
abroad
a. Church music has clearly changed in the diaspora.
i. Women began to participate.
ii. Youth choirs began to sing hymns before and after Mass.
b. New style of sacred music emerged first in Ethiopia.
i. Sunday Schools opened a pathway for women to
become active in Ethiopian Christian worship.
ii. New hymns have proven very popular.
c. Sacred music remains a vital part of the life in the Ethiopian
diaspora.
i. Some musical traditions have been maintained with
great care and at great sacrifice.
ii. Changes in the sound and concept of performance have
been accepted.






* Chapter 9 - Music and Politics

** 1. INTRODUCTION

*** A. Music has always been an integral part of formal displays of political power.

*** B. It has traditionally conveyed both national identity and official ideologies through symbolic acts, such as the singing of a national anthem.
1. Important to recognize the difference between open and coded
political messages
a. Musical displays of power, or public transcripts, often affirm
and perpetuate an existing power structure.
b. Hidden transcripts can be used to describe musical
performances and repertories through metaphorical or coded
terms.
2. Music is crucial in understanding and interpreting how power is
enforced as well as how it is challenged.

*** C. Music can empower people within a particular setting while it is being used and transformed in very different contexts.


** 2. MUSICS OF POWER AND RESISTANCE

*** A. Case Study: The Birth of a National Anthem
1. Music can challenge inequitable power relations.
a. Nkosi Sikel’ iAfrika originated as a Christian hymn and was
transformed into a musical emblem of political resistance.
b. In the 1990s, it became a respected national anthem.
i. Melody was composed by Enoch Mankayi Sontonga, a
choirmaster and teacher at a Methodist mission school
near Johannesburg, South Africa.
ii. The text is sung in several different South African
languages.
iii. Deeply influenced by Western music and harmony

2. Became associated with the African National Congress (ANC)
a. Nelson Mandela was its leader for much of the late twentieth
century.
b. ANC and Nkosi Sikel’ iAfrika were banned by the South African
government as subversive.
c. With Mandela's release from prison and subsequent election to
the presidency, the nation needed a new anthem.
3. For a time, The Call of South Africa and Nkosi Sikelel’ iAfrika were
designated dual national anthems.
a. Nkosi Sikelel’ iAfrika was viewed as an anthem of freedom and
independence throughout Africa.
b. Became the official national anthem of countries such as
Tanzania and Zambia
c. South African government later approved a single, composite
national anthem.

4. Over the years, Nkosi Sikelel’ iAfrika has continued to accrue multiple
layers of meaning:
a. As a Christian hymn
b. As a song of resistance
c. As an integral part of the new South African national anthem

*** B. Case Study: Reggae
1. Ras Tafari became Emperor Haile Selassie of Ethiopia in 1930.
a. Became a widely known and compelling figure to many people
of color in North America and the Caribbean
b. His government's autonomy was challenged by the Italian
invasion in 1935.
i. Provided a symbol for the Rastafarian political and
religious movement
ii. Became closely associated with the musical style known
as reggae
2. Rastafarian movement had its philosophical roots in the 1920s and
the Back to Africa movement.
a. Belief that a black king in Africa would mean deliverance for all
black people
i. Coronation of Ras Tafari as Haile Selassie was
interpreted as the fulfillment of these prophecies.
ii. In the West Indies, an outcome of these events was the
formation of groups supporting the Ethiopian emperor.
Group members believed Haile Selassie’s coronation:
a. Heralded the downfall of “Babylon” (white
colonial powers) and an end to colonial rule
b. Heralded the promised deliverance of oppressed
blacks
b. Rastafarianism provided fertile ground for the development of
powerful rituals and symbols.
i. Green, yellow, and red—the colors of the Ethiopian
flag—were adopted by Rastafarians.
ii. Dreadlock hairstyles
iii. Use of mind-altering substances
3. At first, no single musical style was associated with Rastafarianism.
a. By the early 1960s, a predecessor of reggae called ska was
popular.
i. Based on an indigenous Jamaican rhythm emphasizing
offbeats in quadruple rhythmic pattern
b. Ska was followed in the mid-1960s by rock steady.
i. Slower tempo
ii. Texts discussed freedom and equality
4. In 1968, reggae came on the scene
a. Its name was taken from the song Do the Reggay.

i.

Defined early on as encompassing “poverty, suffering,
Rastafari, everything in the ghetto.”
ii. Derived from the English word “regular.”
b. Rhythm is essential to the Rastafarian reggae tradition: riddim.
i. Riddim is a metaphor for the idea of resistance in the
lyrics.
ii. Some riddims are named, such as cordiroy (corduroy),
bangara (from bhangra), or diwali (a Hindu festival).
5. Reggae musicians have taken strong political stands through their
music.
a. Bob Marley was internationally known and became the
musician most widely associated with reggae and other
Jamaican musics.
b. Reggae has maintained its status as music of political
resistance through various transformations on the
international stage.
i. Reggae entered mass culture through recordings.
ii. Led an increasingly dual life as both a cult and
commercial music
c. The 1990s also saw the emergence of new kinds of localized
reggae styles such as reggaeton.

*** C. Case Study: The Shoshone Powwow
1. The setting of Shoshone Indian Days
a. The first Native American powwow was held in the late
nineteenth century.
i. Algonquian word pawwaw refers to religious
practitioners and healing ceremonies
ii. By 1900, the word was applied to any type of gathering.
b. The modern intertribal powwow has its origins in 1920s
Oklahoma.
i. Large, intertribal powwows became increasingly
widespread over the years.
ii. Today, the number of North American powwows is
estimated at more than two thousand per year.
c. The Eastern Shoshone Indian Days festival is part of the
increasingly well-established "powwow circuit."
i. The powwow takes place in the town of Fort Washakie,
Wyoming.
a. Wooden arbor is the focus of powwow activities.
b. Center of arbor is reserved for dancers.
ii. During the evening hours, the powwow dance
competitions are held.
a. Participants come from throughout the West.
b. Features multiple drum groups that take turns
accompanying the dancers

d. Competitive dances are usually divided into separate
traditional and fancy styles.
i. Fancy and Traditional War Dances for men
a. Main difference between the styles is that there
are added spins and twirls in the choreography
of the Fancy War Dance.
b. Women originally did not dance the War Dance,
but they do today.
ii. The traditional dances have lost some of their
popularity.
a. Fancy War and Fancy Shawl Dances are more
popular with young people.
b. Jingle Dress Dance also is popular.
e. The focus of most modern powwows is the dance competitions.
2. The Flag Song’s sound and significance
a. Every powwow begins with a Grand Entry.
i. Veterans carry the American flag, the state flag, and
banners of the Veterans of Foreign Wars.
a. Flag presentation is accompanied the Flag Song.
b. Solemn ceremony
ii. Shoshone repertory contains many Flag Songs.
a. Native American flag ceremony replaces the
national anthem with Native American song.
b. New Flag Songs commemorate the different
military conflicts in which Native Americans
have served.
3. Honoring warriors in song: the War Dance
a. War Dance songs make overt political statements.
i. Warrior-fighter has given way to the warrior-dancer.
a. Present-day War Dances mimic traditional
fighting movements.
b. Motions sustain the War Dance’s historical
connections to the Wolf Dance.
b. War Dance is also connected to nature.
c. The War Dance Song is the centerpiece of the powwow.
i. Shoshone singers often borrow songs from other
groups.
ii. Sometime borrow from non–Native American sources.
4. The changing settings of powwow music
a. The music of the powwow has also shifted to new settings.
i. Halftime at football games
ii. Rodeos and other ceremonies
b. Reaching new audiences through mass media
c. American Indian Dance Theatre






* Chapter 10 - Music and Identity


** 1. INTRODUCTION

*** A. Among the many elements that define our identities are ethnicity, race, class, gender, and religious orientation.
1. National or regional heritage, language group, political affiliation, and occupation may also contribute.
2. Identity is almost always constructed in relation to groups that we either wish to be part of or seek to distinguish ourselves from.

*** B. Identities are complex formations that rarely stay static.
1. Today, many music traditions remain closely associated with
communities that share background and history.
2. Many aspects of ethnic identity are shaped by descent; others are
determined by consent and consciously chosen through affiliations.

*** C. Musical styles that symbolize identity maintain strong links with the past or with an original homeland.
1. In the twenty-first century, a challenge in charting identity and its
expression through music is the increasing separation of identity
from place.
2. Geographic location is one of many important contextual factors
that may define a soundscape.


** 2. EXPRESSING INDIVIDUAL AND GROUP IDENTITIES THROUGH MUSIC

*** A. Case Study: The Intercultural Music of Composer Lei Liang
1. Lei Liang was born in Tianjin, China in 1972, during China’s
Cultural Revolution.
a. The Cultural Revolution effectively brought independent
composing, performing, teaching, and research to an official
halt.
b. After the Cultural Revolution ended, normal cultural life in
China slowly resumed, and composers were again free to
express themselves creatively.
i. “New wave” Chinese composers graduated from the
Central Conservatory in Beijing and then emigrated to
the West in the early 1980s.
a. The Chinese musical migration has had a
significant international impact on musical
composition.
ii. Lei Liang is one of a younger cohort who were born in
China during or after the Cultural Revolution and who
emigrated to study and compose abroad.
a. Like those of his older colleagues, his
compositions draw on his Chinese heritage.
b. He has constructed his own compositional voice
and honed a “few core concepts” that he believes

cross “historical, cultural, technological, and
disciplinary boundaries.”
2. Liang’s work Gobi Gloria absorbs different cultural influences,
transforms them, and communicates them.
a. The piece is a celebration of Mongolia’s Gobi Desert; the title
refers to the Gloria section of the Roman Catholic Mass.
b. Liang became fascinated by Inner Asian biphonic singing.
i. It inspired his compositional principle of the “shadow.”
ii. “One-note polyphony.”
c. In his concept of “breathing,” Liang follows how the flow of
melody resembles the process of the human breath.
d. In his concept of transformation, Liang approaches sound as a
“living entity, its latent dynamics and hidden forces mirror an
individual’s adaptation in a complex and ever-changing world.”
3. Wenren is a traditional Chinese concept that refers to a philosopherartist whose works that cut across boundaries.
a. Liang’s work is a confluence of Western and Asian cultures
b. The synthesis in Liang’s work draws on processes of descent,
affinity, and close study.
i. The creation of musical hybrids extends beyond the
arena of musical sound to provide insight into personal
and collective identity.

*** B. Case Study: The Multiple Meanings of Karaoke
1. Karaoke ("empty orchestra") originated in 1972 at a snack bar in
Kobe, Japan.
a. Technologically mediated musical performance.
b. Spread throughout Japan and East Asia, later
internationally.
2. Karaoke has been discussed by scholars on several levels:
a. As a performance medium grounded in new technologies
b. As a setting-specific musical genre
c. As a ritualized form of musical behavior
3. Karaoke is closely associated with particular social settings.
a. Originally popular in bars and night clubs; substituted for
live performance
b. Also popular at dinner parties and in private homes
4. In Japan, both social and musical behaviors associated with
karaoke are quite formalized and patterned.
a. Rules for karaoke performance circulate formally in
karaoke journals.
i. Popular list of "seven taboos" in karaoke
ii. Rules are intended to help regulate gender
hierarchies and politeness in public space.
b. Additional hidden rules guarantee decorum and minimize
competition.

5. Karaoke draws on the traditional Japanese value of kata
(“patterned form”).
a. Pervades many Japanese arts.
i. Expressive forms are composed of precise, named
patterns.
ii. Form is considered to be more important than
original content.
b. The kata principle as manifested in a historical musical
style is found in kabuki theater.
i. Kata guides everything.
ii. Kata shapes musical expression.
c. Kata provides the aesthetic framework for repeating a wellknown pattern, an aesthetic that reverberates throughout
karaoke.
6. Karaoke also draws on a long tradition in Japan of communal,
public singing.
a. One Japanese popular song genre, called enka, is
particularly associated with karaoke.
i. Enka is based on stylized formulas.
ii. The karaoke singer of enka must reproduce the
song’s words and music and imitate the original
singer’s style.
iii. Enka promotes shared values and forges group
identity
b. Karaoke has deep roots in traditional Japanese values and
enjoys broad-based popularity in Japan, supported by an
active karaoke culture.
i. The karaoke performance derives its significance
from intimate settings.
7. Karaoke first spread throughout East Asia.
a. Changes were introduced as it was adopted in different
national settings.
b. Others worldwide have adapted karaoke to a variety of
settings.

*** C. Case Study: Multiple Identities in Cajun and Zydeco Musics
1. The French heritage of Creoles and Cajuns
a. Creoles and Cajuns share the same language and the same
geographical region.
b. Both traditions trace their roots to the French-speaking
people who arrived in Louisiana between the sixteenth and
seventeenth centuries.
i. Creoles are a heterogeneous group of people who
are of mixed French, Spanish, and African or AfroCaribbean descent.

ii.

Cajuns arrived later, beginning in 1755. Cajuns
descend from a more homogeneous community of
French refugees who lived in Acadia.
a. Expelled by the British
b. The name “Cajun” derives from the French
adjective acadien, meaning a person from
Acadia.
iii. Present-day musical style most closely associated
with Creole identity—zydeco music—emerged only
in the mid-twentieth century.
2. Setting: musics of place
a. Cajuns sustained their French traditions and language,
which increasingly came into contact with a number of
other peoples and cultures.
i. Gave rise to a rich, distinctive culture and musical
style
ii. The culture and the music, along with the people
themselves, came to be known as Cajun.
iii. Cajuns contributed to other well-known American
musical styles.
b. Ensembles consist of accordion, fiddle, guitar, triangle, and
drums.
i. Fiddle traveled with the Acadians.
ii. Accordion was introduced by German immigrants.
iii. Electric guitars and drum sets were incorporated
into Cajun bands.
c. Emphasis in many Cajun songs is on the sound of the words.
i. Cajun French has declined dramatically.
ii. Cajun song was one of the few means of preserving
the special Cajun French dialect.
d. The button accordion is at the heart of the Cajun sound.
e. The association of Cajun music with dance has played an
important part in keeping Cajun music alive.
3. Sound and significance: singing ethnicity, race, and class
a. Historically, Cajun and Creole cultures have had much in
common.
i. Poor Creoles of color and Cajun whites worked side
by side in the same fields.
a. Prolonged period of cultural exchange
between the groups resulted in culinary and
linguistic blending.
b. Cajun dialect of French took on distinctive
local features.
ii. Cajun and Creole musicians even played together.

b. The division between Cajuns and Creoles extends to their
names for the very places they jointly inhabit.
c. Complicated musical, racial, and cultural interactions
emerged including, after World War II, resulting in a
distinctively Creole music that came to be called zydeco.
i. Zydeco has interacted with other African American
and Caribbean traditions.
ii. Zydeco was at first influenced by Cajun music; later,
zydeco began to influence Cajun musicians more
strongly.
a. Zydeco uses the same core ensemble as Cajun
music.
b. Part of zydeco's distinctive sound came from
a found instrument: a steel washboard or
"rub board."
iii. In black Creole society, as well as in Cajun circles,
music flourished in bals de maison (house dances).
4. Zydeco's kings and queens
a. The use of the titles “king” and “queen” comes from Joe
Falcon, who called himself the “Famous Columbia Record
King.”
i. Zydeco kings ruled this male-dominated tradition.
ii. Very few women were able to make careers as
zydeco musicians.
b. Ida Guillory is an exception among zydeco musicians.
i. Queen Ida's musical style embodies all the hallmarks
of zydeco.
ii. Virtuoso accordion player
5. Raising Creole voices, reviving Creole roots
a. Interaction between Cajuns and Creoles is once again
emerging.
b. New bands are now bridging the racial and musical gap.




